pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./wprowadzenie.html","Introduction","Introduction INTEGRUM has been developed for management of multiple alarm systems based on INTEGRA and INTEGRA Plus control panels. The INTEGRUM s...",""],
["./menu-glowne.html","Menu główne","Menu główne Enter topic text here. ",""],
["./menu-regionow.html","Regions menu","Regions menu You can group the alarm systems by any criteria within the units that are conventionally called regions. It is easier to manage a lar...",""],
["./ekran_uzytkownicy.html","&#8220;Users&#8221; screen","&#8220;Users&#8221; screen The screen presents the list of INTEGRUM users and allows you to manage them. The INTEGRUM users can be: users of the INTEGRUM appl...",""],
["./ekran-z-danymi-uzytkownika.html","User data screen","User data screen The screen presents data of the INTEGRUM user and allows you to manage the user settings. At the top of the screen the Menu bar i...",""],
["./dodanie-nowego-uzytkownika.html","Adding a new user (&#8220;Users&#8221; screen)","Adding a new user (&#8220;Users&#8221; screen) 1.Click on . 2.The &#8220;New user&#8221; screen will appear. 3.If you want to add a user to another region than that sugge...",""],
["./ekran_centrale.html","&#8220;Control panels&#8221; screen","&#8220;Control panels&#8221; screen The screen presents the list of INTEGRA / INTEGRA Plus control panels registered in the INTEGRUM system and allows you to ...",""],
["./ekran-z-danymi-centrali.html","Control panel data screen","Control panel data screen The screen presents data of the control panel registered in the INTEGRUM system and allows management of the alarm syste...",""],
["./ekran-z-danymi-modulu-ethernet.html","Ethernet module data screen","Ethernet module data screen The screen presents data of the Ethernet module through which communication between INTEGRUM and alarm control panel t...",""],
["./okno-edycja.html","&#8220;Edit&#8221; window","&#8220;Edit&#8221; window [user name] - user name in the alarm control panel. Hover the cursor over the icon to see the user number in the alarm control panel...",""],
["./zarzadzanie-centralami-alarmow.html","Managing the alarm control panels","Managing the alarm control panels Adding a new control panel Assigning a control panel to another region Deleting a control panel ",""],
["./dodanie-nowej-centrali.html","Adding a new control panel","Adding a new control panel The new control panel is added to the region whose name is displayed on the &#8220;Control panels&#8221; screen. 1.On the &#8220;Control ...",""],
["./przydzielenie-centrali-do-inne.html","Assigning a control panel to another region","Assigning a control panel to another region 1.On the &#8220;Control panels&#8221; screen, click on in the line in which information about the control panel is...",""],
["./usuniecie-centrali.html","Deleting a control panel","Deleting a control panel 1.On the &#8220;Control panels&#8221; screen, click on in the line in which information about the control panel is displayed. 2.In th...",""],
["./zarzadzanie-uzytkownikami-cent.html","Managing the alarm control panel users","Managing the alarm control panel users 1.On the &#8220;Control panels&#8221; screen, click on in the line which displays information about the control panel t...",""],
["./dodanie-uzytkownika-centrale.html","Adding a user to the alarm control panel (&#8220;Control panels&#8221; screen)","Adding a user to the alarm control panel (&#8220;Control panels&#8221; screen) 1.Click on . 2.The &#8220;Add&#8221; window will appear. Adding an INTEGRUM user 1.Click on...",""],
["./dodanie-do-integrum-centrale.html","Adding alarm control panel user to the INTEGRUM database (&#8220;Control panels&#8221; screen)","Adding alarm control panel user to the INTEGRUM database (&#8220;Control panels&#8221; screen) 1.Click on the name of the alarm control panel user whom you wa...",""],
["./powiazanie-uzytkownika-central.html","Linking alarm control panel user with INTEGRUM user (&#8220;Control panels&#8221; screen)","Linking alarm control panel user with INTEGRUM user (&#8220;Control panels&#8221; screen) 1.Click on the name of the alarm control panel user whom you want to...",""],
["./ekran-zdarzenia.html","&#8220;Event log&#8221; screen","&#8220;Event log&#8221; screen The screen presents the list of events read from the control panels registered in the INTEGRUM system or generated by the INTEG...",""],
["./zmiana-powiazania-centrale.html","Zmiana powiązania użytkowników (ekran &#8222;Centrale&#8221;)","Zmiana powiązania użytkowników (ekran Centrale&#8221;) Enter topic text here. ",""],
["./usuniecie-powiazania-centrale.html","Unlinking users (&#8220;Control panels&#8221; screen)","Unlinking users (&#8220;Control panels&#8221; screen) 1.Click on the INTEGRUM user name (or on in the line in which data of that user are displayed). 2.The &#8220;E...",""],
["./usuniecie-uzytkownika-centrale.html","Deleting a user from alarm control panel (&#8220;Control panels&#8221; screen)","Deleting a user from alarm control panel (&#8220;Control panels&#8221; screen) 1.Click on in the line in which data of the user whom you want to remove from t...",""],
["./zarzadzanie-kartami-centrale.html","Managing the proximity cards","Managing the proximity cards The alarm control panel user can have a proximity card (passive transponder 125 kHz which comes in the form of a card...",""],
["./filtrowanie-listy-central.html","Filtering the list of control panels","Filtering the list of control panels The filtering function makes it possible to display on the &#8220;Control panels&#8221; screen only those control panels ...",""],
["./filtrowanie-nazwy-centrali.html","Filtering by control panel name","Filtering by control panel name 1.Click on the &#8220;Name&#8221; field and enter a string of characters that is to be included in the control panel name. 2.P...",""],
["./filtrowanie-adres-modulu.html","Filtering by Ethernet module address","Filtering by Ethernet module address 1.Click on the &#8220;Address&#8221; field and enter the string of characters which is to be included in the network addr...",""],
["./filtrowanie-status-centrali.html","Filtering by control panel status","Filtering by control panel status Click on one of the icons by which the columns of status indicators are designated. Depending on which icon you ...",""],
["./ekran-powitalny.html","Welcome screen","Welcome to INTEGRUM Welcome to the INTEGRUM user&#39;s application. Thank you for choosing our product. We wish you satisfaction of your choice and wo...",""],
["./pierwsze-kroki.html","First steps (administrator)","First steps (administrator) After the first login to the application: 1.Change the application access password (see Changing the INTEGRUM applicat...",""],
["./zmiana-hasla-dostepu.html","Changing the INTEGRUM application password","Changing the INTEGRUM application password 1.Click on in the main menu. 2.A screen with your INTEGRUM system settings will be displayed. 3.In the ...",""],
["./pasek-menu.html","Menu bar","Menu bar The menu bar displays the main menu. - click to display the regions menu . - click to display the &#8220;Users&#8221; screen. - click to display the ...",""],
["./ekran-ustawienia-regionu.html","&#8220;Region settings&#8221; screen","&#8220;Region settings&#8221; screen - click to add a new region (see Creating a new region ). Name - individual name of the region. Belongs to - region to wh...",""],
["./zarzadzanie-regionami.html","Managing regions","Managing regions Creating a new region Editing a region Deleting a region ",""],
["./utworzenie-nowego-regionu.html","Creating a new region","Creating a new region 1.On the &#8220;Region settings&#8221; screen, click on . 2.Enter individual name of the new region. 3.Select the region to which the ne...",""],
["./edycja-regionu.html","Editing a region","Editing a region 1.In the regions menu, click on the region you want to edit. 2.Change the region name in the &#8220;Name&#8221; field or select another regio...",""],
["./usuniecie-regionu.html","Deleting a region","Deleting a region 1.In the regions menu, click on the region you want to delete. 2.Click on . 3.In the window that will open, click on &#8220;Delete&#8221; to...",""],
["./uzytkownik-aplikacji-integrum.html","INTEGRUM application user","INTEGRUM application user The INTEGRUM application user has: login - a string of characters for identification of the user. password - a string of...",""],
["./uzytkownik-centrali-alarmowej.html","INTEGRA alarm control panel user","INTEGRA alarm control panel user For information on the users of INTEGRA control panels, please refer to the manuals of INTEGRA and INTEGRA Plus c...",""],
["./zarzadzanie-uz-integrum.html","Managing the INTEGRUM users","Managing the INTEGRUM users Adding a new user (&#8220;Users&#8221; screen) Granting access to the INTEGRUM application (&#8220;Users&#8221; screen) Revoking access to the...",""],
["./przyznanie-dostepu-integrum-u.html","Granting access to the INTEGRUM application (&#8220;Users&#8221; screen)","Granting access to the INTEGRUM application (&#8220;Users&#8221; screen) 1.Click on in the line in which information about the user is displayed. 2.The &#8220;Gener...",""],
["./pozbawienie-dostepu-integrum-u.html","Revoking access to the INTEGRUM application (&#8220;Users&#8221; screen)","Revoking access to the INTEGRUM application (&#8220;Users&#8221; screen) 1.Click on in the line in which information about the user is displayed. 2.The &#8220;Gener...",""],
["./dodanie-uz-do-centrali-u.html","Adding a user to the alarm control panel (&#8220;Users&#8221; screen)","Adding a user to the alarm control panel (&#8220;Users&#8221; screen) 1.Click on in the line in which information about the user is displayed. 2.The &#8220;Access t...",""],
["./usuniecie-uz-z-centrali-u.html","Deleting a user from alarm control panel (&#8220;Users&#8221; screen)","Deleting a user from alarm control panel (&#8220;Users&#8221; screen) 1.Click on in the line in which the information about the user is displayed. 2.The &#8220;Acce...",""],
["./edycja-uzytkownika-u.html","Editing a user (&#8220;Users&#8221; screen)","Editing a user (&#8220;Users&#8221; screen) Click on one of the following buttons in the line in which information about the user you want to edit is displaye...",""],
["./przeniesienie-uz-do-archiwum-u.html","Moving a user to archive (&#8220;Users&#8221; screen)","Moving a user to archive (&#8220;Users&#8221; screen) 1.Click on in the line in which information about the user you want to move to archive is displayed. 2.I...",""],
["./przywrocenie-archiwalnego-uz-u.html","Restoring an archive user (&#8220;Users&#8221; screen)","Restoring an archive user (&#8220;Users&#8221; screen) 1.Click on to display the list of archive users. 2.Click on in the line in which information about the ...",""],
["./filtrowanie-listy-uzytkownikow.html","Filtering the user list","Filtering the user list The filtering function makes it possible to display on the &#8220;Users&#8221; screen only the users that meet some specified criteria...",""],
["./filtrowanie-wg-nazwy-uzytkownika.html","Filtering by user name","Filtering by user name 1.Click on the &#8220;Name&#8221; field and enter the string of characters that is to be included in the user name. 2.Press ENTER or cl...",""],
["./filtrowanie-wg-adresu-e-mail.html","Filtering by user e-mail address","Filtering by user e-mail address 1.Click on the &#8220;E-mail&#8221; field and enter the string of characters that is to be included in the user e-mail addres...",""],
["./filtrowanie-wg-numeru-telefonu.html","Filtering by user phone number","Filtering by user phone number 1.Click on the &#8220;Telephone&#8221; field and enter the string of characters that is to be included in the user telephone nu...",""],
["./filtrowanie-wg-statusu-uzytkownika.html","Filtering by user status","Filtering by user status Click on one of the icons by which the status indicator columns are designated. Depending on the icon you clicked, only t...",""],
["./filtrowanie-wedlug-centrali.html","Filtering by control panel","Filtering by control panel 1.Click on to display additional fields for defining the list filtering criteria. 2.Click on the &#8220;Control panels&#8221; field...",""],
["./filtrowanie-wg-uprawnien-uzytk.html","Filtering by user rights","Filtering by user rights 1.Click on to display additional fields for defining the list filtering criteria. 2.Click on the &#8220;Rights&#8221; field. 3.The li...",""],
["./dodanie-karty-zblizeniowej.html","Adding a proximity card","Adding a proximity card 1.Click on . 2.The &#8220;Manage card&#8221; window will open. Adding a proximity card by using computer only 1.In the &#8220;Reader&#8221; field,...",""],
["./zastapienie-karty-zblizeniowej.html","Replacing a proximity card with another","Replacing a proximity card with another 1.Click on . 2.The &#8220;Manage card&#8221; window will open. 3.Proceed in the same way as when adding a proximity ca...",""],
["./usuniecie-karty-zblizeniowej.html","Deleting a proximity card","Deleting a proximity card 1.Click on . 2.The &#8220;Manage card&#8221; window will open. 3.Click on next to the &#8220;Card number&#8221; field. 4.In the window that will...",""],
["./okno-komentarzy.html","Comments window","Comments window At the top of the window, information about the event is displayed (description, date and time of occurrence, details). [control p...",""],
["./filtrowanie-listy-zdarzen.html","Filtering the event list","Filtering the event list The filtering function makes it possible to display on the &#8220;Event log&#8221; screen only those events that meet the specified c...",""],
["./filtrowanie-wedlug-czasu-zdarz.html","Filtering by event occurrence time","Filtering by event occurrence time 1.Click on the &#8220;Date&#8221; button. 2.Fields that allow filtering by event occurrence time will be displayed. 3.If ev...",""],
["./filtrowanie-wedlug-zrodla-zdar.html","Filtering by event source","Filtering by event source 1.Click on the &#8220;Source&#8221; field. 2.In the field that will be displayed, enter at least 1 character. 3.The list of alarm co...",""],
["./filtrowanie-wedlug-typu-zdarze.html","Filtering by event type","Filtering by event type 1.Click on the &#8220;Type&#8221; button. 2.The list of buttons designated by event type icons will be displayed. 3.Click on the butto...",""],
["./filtrowanie-wedlug-opisu-zdarz.html","Filtering by event description","Filtering by event description 1.Click on the &#8220;Event&#8221; field. 2.The list of event descriptions will be displayed (it is created based on the events...",""],
["./filtrowanie-wedlug-uzytkownika.html","Filtering by user","Filtering by user 1.Click on the &#8220;User&#8221; field. 2.The list of users will be displayed. If the user is not included in the INTEGRUM database, inform...",""],
["./filtrowanie-wedlug-komentarzy.html","Filtering by comments","Filtering by comments 1.Click on to display additional fields for defining the list filtering criteria. 2.Select the events that are to be display...",""],
["./ekran-tablica-informacyjna.html","&#8220;Dashboard&#8221; screen","&#8220;Dashboard&#8221; screen The screen provides information about the status of alarm systems registered in INTEGRUM. The information is presented in six w...",""],
["./okno-wykres.html","&#8220;Diagram&#8221; window","&#8220;Diagram&#8221; window The window presents in graphic form the information on status of the alarm systems registered in INTEGRUM. The title bar displays...",""],
["./okno-szczegoly.html","&#8220;Details&#8221; window","&#8220;Details&#8221; window Content of the window changes depending on operations performed in other windows. The window may display the list of control pane...",""],
["./okno-mapa.html","&#8220;Map&#8221; window","&#8220;Map&#8221; window The window presents in graphic form information about location and status of the alarm systems registered in INTEGRUM. The maps must ...",""],
["./obiekty-na-mapie.html","Items on the map","Items on the map The following items may be on the map: map (link to another map), partition, zone, camera. Map The link to another map is present...",""],
["./przyciski.html","Buttons","Buttons - click to go to the map belonging to parent level region. - click to zoom in the map. - click to zoom out the map. - click to fit the map...",""],
["./panel-prezentujacy-liste-obiek.html","Panel presenting the list of items","Panel presenting the list of items At the bottom right corner of the &#8220;Map&#8221; window, the map name is displayed. Clicking on the map name will displa...",""],
["./okno-zdarzenia.html","&#8220;Events&#8221; window","&#8220;Events&#8221; window The window presents events of a specified type. Information about the event type is displayed on the title bar. The type of events...",""],
["./okno-komentowania.html","Commenting window","Commenting window The window, which appears automatically after an event of alarm or trouble type is downloaded from the alarm control panel, allo...",""],
["./ekran-status.html","&#8220;Status&#8221; screen","&#8220;Status&#8221; screen The screen presents information about the INTEGRUM system status and allows you to manage licenses. The Menu bar is displayed at t...",""],
["./ekran-moduly-ethernetowe.html","&#8220;Ethernet modules&#8221; screen","&#8220;Ethernet modules&#8221; screen Screen presents the list of Ethernet modules though which communication with the alarm control panels registered in the ...",""],
["./filtrowanie-listy-modulow-ethe.html","Filtering the list of Ethernet modules","Filtering the list of Ethernet modules The filtering function makes it possible to display only the modules which meet the specified criteria. You...",""],
["./filtrowanie-wedlug-nazwy-eth.html","Filtering by Ethernet module name","Filtering by Ethernet module name 1.Click on the &#8220;Name&#8221; field and enter a string of characters that is to be included in the module name. 2.Press ...",""],
["./filtrowanie-wedlug-adresu-eth.html","Filtering by Ethernet module address","Filtering by Ethernet module address 1.Click on the &#8220;Address&#8221; field and enter a string of characters that is to be included in the network address...",""],
["./filtrowanie-wedlug-statusu-eth.html","Filtering by Ethernet module status","Filtering by Ethernet module status Click on one of the icons by which the status indicator columns are designated. Depending which icon you have ...",""],
["./uzyskanie-licencji.html","Obtaining a license","Obtaining a license Management of the alarm systems is possible after obtaining a license (a new alarm system can only be used for one hour withou...",""],
["./ekran-szablony-uzytkownikow.html","&#8220;User schedules&#8221; screen","&#8220;User schedules&#8221; screen The screen presents information about the schedules of alarm control panel user defined in INTEGRUM and allows you to mana...",""],
["./zarzadzanie-szablonami-uzytkow.html","Managing the alarm control panel user schedules","Managing the alarm control panel user schedules Creating an alarm control panel user schedule Editing an alarm control panel user schedule Deletin...",""],
["./utworzenie-szablonu-uzytkownik.html","Creating an alarm control panel user schedule","Creating an alarm control panel user schedule 1.Click on . 2.Select the user type in the &#8220;User type&#8221; field. 3.Select the rights in the &#8220;Rights&#8221; fi...",""],
["./edycja-szablonu-uzytkownika-ce.html","Editing an alarm control panel user schedule","Editing an alarm control panel user schedule 1.In the &#8220;Name&#8221; field, click on the name of the schedule you want to edit. 2.Select another user type...",""],
["./usuniecie-szablonu-uzytkownika.html","Deleting an alarm control panel user schedule","Deleting an alarm control panel user schedule 1.In the &#8220;Name&#8221; field, click on the name of the schedule you want to remove. 2.Click on . 3.In the w...",""],
["./ekran-role-uzytkownikow.html","&#8220;User roles&#8221; screen","&#8220;User roles&#8221; screen The screen presents information about defined roles of the INTEGRUM application users and allows you to manage the user roles....",""],
["./opis-funkcji-integrum.html","Description of functions available to INTEGRUM application users","Description of functions available to INTEGRUM application users Access to dashboard - the function allows you to access the &#8220;Dashboard&#8221; screen. O...",""],
["./zarzadzanie-rolami-uzytkownika.html","Managing the INTEGRUM application user roles","Managing the INTEGRUM application user roles Creating an INTEGRUM application user role Editing an INTEGRUM application user role Deleting an INTE...",""],
["./utworzenie-roli-uzytkownika-ap.html","Creating an INTEGRUM application user role","Creating an INTEGRUM application user role 1.Click on . 2.Select functions in the &#8220;Functions&#8221; field. 3.Click on . 4.The &#8220;New role&#8221; window will app...",""],
["./edycja-roli-uzytkownika-aplika.html","Editing an INTEGRUM application user role","Editing an INTEGRUM application user role 1.In the &#8220;Name&#8221; field, click on the name of the role you want to edit. 2.Select or deselect functions in...",""],
["./usuniecie-roli-uzytkownika-apl.html","Deleting an INTEGRUM application user role","Deleting an INTEGRUM application user role 1.In the &#8220;Name&#8221; field, click on the name of the role you want to delete. 2.Click on . 3.In the window t...",""]];
